main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('select-workspace/', views.select_workspace, name='select_workspace'),
    path('business_entities/', views.business_entities, name='business_entities'),
    path('business_entities/<int:id>', views.business_entity_detail, name='business_entity_detail'),
    path('product-items/', views.product_items, name='product_items'),
    path('product-items/<int:id>', views.product_item_detail, name='product_item_detail'),
    path('stock/', views.stock_entries, name='stock_entries'),
    path('stock/<int:id>', views.stock_entry_detail, name='stock_entry_detail'),
    path('vetis-task/', views.vetis_task, name='vetis_task'),
    path('task-info/', views.task_info, name='task_info'),
]

vetis_api/urls.py
from django.urls import path
from . import views


app_name = 'vetis_api'

urlpatterns = [
    path('history/', views.api_requests_history, name='api_requests_history'),
    path('history/<int:id>', views.api_requests_history_detail, name='api_requests_history_detail'),
]

vetis_tools/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('vetis_api.urls')),

    # Django auth
    # https://docs.djangoproject.com/en/5.2/topics/auth/default/#module-django.contrib.auth.views
    # path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    vetis_login = models.CharField(null=True, blank=True, max_length=20, verbose_name='логин Ветис')
    
    def get_display_name(self):
        return self.get_full_name() or self.get_username()
    

vetis_api/models.py
from datetime import datetime, timezone, timedelta

from django.db import models
from django.core.exceptions import ObjectDoesNotExist

from main.models import User


PRODUCT_TYPES = (
    (1, 'Мясо и мясопродукты'),
    (2, 'Корма и кормовые добавки'),
    (3, 'Живые животные'),
    (4, 'Лекарственные средства'),
    (5, 'Пищевые продукты'),
    (6, 'Непищевые продукты и другое'),
    (7, 'Рыба и морепродукты'),
    (8, 'Продукция, не требующая разрешения'),
)

TZ_MOSCOW = timezone(timedelta(hours=3))


class ApiRequestsHistoryRecord(models.Model):
    datetime = models.DateTimeField(auto_now_add=True, verbose_name='метка времени')
    soap_action = models.CharField(null=True, max_length=30, verbose_name='SOAP action')
    soap_request = models.TextField(null=True, verbose_name='текст запроса')
    response_status_code = models.IntegerField(null=True, verbose_name='статус ответа')
    response_body = models.TextField(null=True, verbose_name='текст ответа')
    comment = models.CharField(null=True, max_length=255, verbose_name='комментарий')
    user = models.ForeignKey(User, null=True, on_delete=models.PROTECT, verbose_name='пользователь')

    def __str__(self):
        return f'{self.soap_action} ({self.response_status_code})'
    
    class Meta:
        verbose_name = 'запись истории запросов'
        verbose_name_plural = 'записи истории запросов'
        ordering = ['-datetime']


class VetisCredentials(models.Model):
    name = models.CharField(max_length=100, verbose_name='название')
    is_productive = models.BooleanField(default=False, verbose_name='продуктивный')
    login = models.CharField(verbose_name='логин')
    password = models.CharField(verbose_name='пароль')
    api_key = models.CharField(verbose_name='API key')
    service_id = models.CharField(verbose_name='service ID')
    issuer_id = models.CharField(verbose_name='issuer ID')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'подключение Ветис'
        verbose_name_plural = 'подключения Ветис'
        ordering = ['name']


class BusinessEntity(models.Model):
    TYPE_CHOICES = (
        (1, 'Юрлицо'),
        (2, 'Физлицо'),
        (3, 'ИП'),
    )
    guid = models.UUIDField(editable=True, unique=True, db_index=True)
    uuid = models.UUIDField(editable=True, unique=True)
    type = models.IntegerField(choices=TYPE_CHOICES, verbose_name='тип') # get_type_display in templates
    name = models.CharField(max_length=255, verbose_name='имя')
    short_name = models.CharField(max_length=30, null=True, blank=True, verbose_name='имя (кратко)')
    inn = models.CharField(blank=True, max_length=20, verbose_name='ИНН')
    address = models.CharField(blank=True, max_length=255, verbose_name='адрес')
    credentials = models.ForeignKey(VetisCredentials, null=True, verbose_name='параметры подключения', on_delete=models.PROTECT)
    is_active = models.BooleanField(default=True, verbose_name='активен')

    def __str__(self):
        return self.short_name if self.short_name else f'{self.name} ({self.inn})'
    
    class Meta:
        verbose_name = 'хозяйствующий субъект'
        verbose_name_plural = 'хозяйствующие субъекты'
        ordering = ['name']


class Enterprise(models.Model):
    TYPE_CHOICES = (
        (1, 'предприятие'),
        (2, 'рынок'),
        (3, 'СББЖ'),
        (4, 'судно'),
    )
    business_entity = models.ForeignKey(BusinessEntity, on_delete=models.PROTECT, verbose_name='хозяйствующий субъект')
    guid = models.UUIDField(editable=True, unique=True, db_index=True)
    uuid = models.UUIDField(editable=True, unique=True)
    type = models.IntegerField(choices=TYPE_CHOICES, verbose_name='тип') # get_type_display in templates
    name = models.CharField(max_length=255, verbose_name='имя')
    number_list = models.CharField(blank=True, verbose_name='номера предприятия')
    address = models.CharField(blank=True, max_length=255, verbose_name='адрес')
    is_active = models.BooleanField(default=True, verbose_name='активно')
    is_allowed = models.BooleanField(default=False, verbose_name='разрешено работать через АПИ')
    stock_entries_last_updated = models.DateTimeField(null=True, blank=True, verbose_name='последнее обновление журнала')

    def __str__(self):
        return f'{self.name} ({self.address})'
    
    class Meta:
        verbose_name = 'предприятие'
        verbose_name_plural = 'предприятия'
        ordering = ['name']


class BusinessEntityInfo(models.Model):
    guid = models.UUIDField(primary_key=True)
    uuid = models.UUIDField()
    name = models.CharField(max_length=255, verbose_name='имя')
    inn = models.CharField(blank=True, max_length=20, verbose_name='ИНН')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='дата обновления')

    def __str__(self):
        return f'{self.name} ({self.inn})'
    
    class Meta:
        verbose_name = 'хозяйствующий субъект (инфо)'
        verbose_name_plural = 'хозяйствующие субъекты (инфо)'
        ordering = ['name']


class EnterpriseInfo(models.Model):
    guid = models.UUIDField(primary_key=True)
    uuid = models.UUIDField()
    name = models.CharField(max_length=255, verbose_name='имя')
    address = models.CharField(blank=True, max_length=255, verbose_name='адрес')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='дата обновления')

    def __str__(self):
        return f'{self.name} ({self.address})'
    
    class Meta:
        verbose_name = 'предприятие (инфо)'
        verbose_name_plural = 'предприятия (инфо)'
        ordering = ['name']


class Product(models.Model):
    guid = models.UUIDField(unique=True, db_index=True)
    uuid = models.UUIDField(unique=True)
    name = models.CharField(max_length=255, verbose_name='название')
    code = models.CharField(blank=True, max_length=255, verbose_name='код ТН ВЭД')
    product_type = models.IntegerField(choices=PRODUCT_TYPES, verbose_name='тип продукции')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'продукция'
        verbose_name_plural = 'продукция'
        ordering = ['name']


class SubProduct(models.Model):
    guid = models.UUIDField(unique=True, db_index=True)
    uuid = models.UUIDField(unique=True)
    name = models.CharField(max_length=255, verbose_name='название')
    code = models.CharField(blank=True, max_length=255, verbose_name='код ТН ВЭД')
    product_guid = models.UUIDField(verbose_name='продукция (GUID)')
    product = models.ForeignKey(Product, null=True, verbose_name='продукция', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'вид продукции'
        verbose_name_plural = 'виды продукции'
        ordering = ['name']


class ProductItem(models.Model):
    guid = models.UUIDField(unique=True, db_index=True)
    uuid = models.UUIDField(unique=True)
    is_active = models.BooleanField(default=True, verbose_name='активно')
    name = models.CharField(max_length=255, verbose_name='название')
    gtin = models.CharField(blank=True, max_length=20, verbose_name='GTIN')
    product_type = models.IntegerField(choices=PRODUCT_TYPES, verbose_name='тип продукции')
    product_guid = models.UUIDField(verbose_name='продукция (GUID)')
    product = models.ForeignKey(Product, null=True, verbose_name='продукция', on_delete=models.PROTECT)
    subproduct_guid = models.UUIDField(verbose_name='вид продукции (GUID)')
    subproduct = models.ForeignKey(SubProduct, null=True, verbose_name='вид продукции', on_delete=models.PROTECT)
    is_gost = models.BooleanField(default=False, verbose_name='соответствует ГОСТ')
    gost = models.CharField(blank=True, max_length=255, verbose_name='ГОСТ')
    producer_guid = models.UUIDField(blank=True, null=True, verbose_name='производитель (GUID)')
    producer = models.ForeignKey(BusinessEntity, null=True, verbose_name='производитель', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'наименование продукции'
        verbose_name_plural = 'наименования продукции'
        ordering = ['name']


class Unit(models.Model):
    guid = models.UUIDField(unique=True)
    name = models.CharField(max_length=255, verbose_name='название')

    # TODO implement native get_or_create logic https://docs.djangoproject.com/en/5.2/ref/models/querysets/#get-or-create
    @classmethod
    def get_or_create(cls, guid: str, name: str):
        try:
            unit = cls.objects.get(guid=guid)
        except ObjectDoesNotExist:
            unit = cls.objects.create(guid=guid, name=name)
        return unit

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'единица измерения'
        verbose_name_plural = 'единицы измерения'
        ordering = ['name']


class ComplexDate():
    """
    Contains required year, month and optional day, hour.
    String representation: dd.mm.yyyy:hh
    """

    def __init__(self, year: int, month: int, day: int = None, hour: int = None):
        self._year = year
        self._month = month
        self._day = day
        self._hour = hour

        if not self.is_valid():
            raise ValueError()
        
        self.date_str = self.to_string()


    @classmethod
    def from_string(cls, str: str):
        year = None
        month = None
        day = None
        hour = None
        
        try:
            date, time = str.split(':')
        except:
            date = str
            time = None
        
        date_list = date.split('.')

        if len(date_list) == 3:
            day = int(date_list.pop(0))
        
        month = int(date_list[0])
        year = int(date_list[1])
        
        if time:
            hour = int(time)

        return cls(year, month, day, hour)
    

    def __str__(self):
        return self.date_str
    

    def update(self, what: str, value: int):
        if what == 'year':
            self._year = value

main/forms.py
from django import forms
from django.urls import reverse_lazy

from vetis_api.models import BusinessEntity, Enterprise, Product


class WorkspaceSelectionForm(forms.Form):
    business_entity = forms.ModelChoiceField(
        queryset=BusinessEntity.objects.exclude(credentials=None),
        required=True,
        label='Хозяйствующий субъект',
        widget=forms.Select(attrs={'hx-get': reverse_lazy('main:select_workspace'), 'hx-target': '#enterprise'})  # reverse('main:enterprise_options')
        )
    enterprise = forms.ModelChoiceField(queryset=Enterprise.objects.all(), label='Предприятие', required=False)


class ProductItemsFilterForm(forms.Form):
    business_entity = forms.ModelChoiceField(queryset=BusinessEntity.objects.all(), label='Владелец', required=False)
    search_query = forms.CharField(max_length=100, label='Название', required=False, widget=forms.widgets.TextInput(attrs={'autocomplete': 'off'}))
    by_groups = forms.BooleanField(label='По группам', required=False)


class StockEntriesFilterForm(forms.Form):
    search_query = forms.CharField(max_length=100, label='Наименование', required=False, widget=forms.widgets.TextInput(attrs={'autocomplete': 'off'}))
    product = forms.ModelChoiceField(queryset=Product.objects.all(), label='Продукция', required=False)
    has_quantity = forms.BooleanField(label='Непустые', initial=True, required=False)
    date_produced_begin = forms.DateField(label='Выпущено с', required=False, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_produced_end = forms.DateField(label='Выпущено по', required=False, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_created_begin = forms.DateField(label='Изменено с', required=False, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_created_end = forms.DateField(label='Изменено по', required=False, widget=forms.widgets.DateInput(attrs={'type': 'date'}))


class StockEntryCommentForm(forms.Form):
    important = forms.BooleanField(required=False, label='Важно')
    text = forms.CharField(max_length=255, required=False, label='Комментарий', widget=forms.widgets.TextInput(attrs={'autocomplete': 'off'}))

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Инструменты Ветис{% endblock %}</title>
    <!-- <link rel="icon" href="./favicon.ico" type="image/x-icon"> -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js" integrity="sha384-ZBXiYtYQ6hJ2Y0ZNoYuI+Nq5MqWBr+chMrS/RkXpNzQCApHEhOt2aY8EJgqwHLkJ" crossorigin="anonymous"></script>

    <!-- <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}" /> -->
  </head>

  <body>
    {% block navigation %}
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-md">
          <a class="navbar-brand" href="{% url 'main:index' %}">VETIS-TOOLS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:stock_entries' %}">СКЛАД</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">ВЫПУСК</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">СПРАВОЧНИКИ</a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item" href="{% url 'main:business_entities' %}">Хозяйствующие субъекты</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'main:product_items' %}">Наименования продукции</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">API</a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item" href="{% url 'main:vetis_task' %}">Задачи</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'vetis_api:api_requests_history' %}">История запросов</a>
                  </li>
                </ul>
              </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
              {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.get_display_name }}</a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="{% url 'main:select_workspace' %}">Выбрать подключение</a>
                    </li>
                    {% if user.is_staff %}
                      <li>
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Админка</a>
                      </li>
                    {% endif %}
                    <li>
                      <hr class="dropdown-divider" />
                    </li>
                    <li>
                      <form action="{% url 'logout' %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" value="logout" class="dropdown-item">Выйти</button>
                      </form>
                    </li>
                  </ul>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">ВОЙТИ</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    {% endblock %}

    {% block workspace %}
      <div class="bg-body-secondary">
        <div class="container-md text-center text-truncate">
          <a class="link-warning link-underline link-underline-opacity-0 link-opacity-75 link-underline-opacity-100-hover link-opacity-100-hover" style="font-size: 80%;" href="{% url 'main:select_workspace' %}">
            {% if request.session.workspace_name %}
              {{ request.session.workspace_name }}
            {% else %}
              ВЫБРАТЬ ПОДКЛЮЧЕНИЕ
            {% endif %}
          </a>
        </div>
      </div>
    {% endblock %}

    <div class="container-md">
      {% block messages %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert {{ message.tags }} mt-3 alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" label="Закрыть"></button>
            </div>
          {% endfor %}
        {% endif %}
      {% endblock %}

      {% block content %}
        <!-- default content text (typically empty) -->
      {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/business_entities.html
{% extends 'main/base.html' %}

{% block title %}Хозяйствующие субъекты{% endblock %}

{% block content %}
  <h3 class="mt-3">Хозяйствующие субъекты</h3>
  {% for business_entity in business_entities %}
    {% include 'main/includes/business_entity_card.html' %}
  {% empty %}
    <div class="alert alert-info mt-3" role="alert">Нет записей...</div>
  {% endfor %}
{% endblock %}

main/templates/main/stock_entry_detail.html
{% extends 'main/base.html' %}

{% block title %}Запись складского журнала{% endblock %}

{% block content %}
  <h3 class="mt-3">Запись складского журнала</h3>
  
  <table class="table">
    <tbody>
      <tr>
        <th scope="row">Предприятие</th>
        <td>
          {{ stock_entry.enterprise }}
          <a href="{% url 'main:business_entity_detail' stock_entry.enterprise.business_entity.id %}" title="Карточка хозяйствующего субъекта"><i class="bi bi-eye"></i></a>
        </td>
      </tr>
      <tr>
        <th scope="row">Номер записи</th>
        <td>
          {{ stock_entry.entry_number }}
          {% if not stock_entry.is_last %}<span class="badge text-bg-warning">НЕПОСЛЕДНЯЯ ВЕРСИЯ</span>{% endif %}
          {% if not stock_entry.is_active %}<span class="badge text-bg-secondary">неактивна</span>{% endif %}
        </td>
      </tr>
      {% if stock_entry.main.is_populated %}
        <tr>
          <th scope="row">Запись создана</th>
          <td>
            <div>{{ stock_entry.main.date_created }}</div>
            <div style="font-size: 75%;" class="text-secondary">{{ stock_entry.main.get_initial_status_display }}: {{ stock_entry.main.source_be_name }} / {{ stock_entry.main.source_ent_name }}</div>
          </td>
        </tr>
      {% endif %}
      <tr>
        <th scope="row">Версия создана</th>
        <td>
          {{ stock_entry.date_created }}
          <span class="badge text-bg-info">{{ stock_entry.get_status_display }}</span>
        </td>
      </tr>
      <tr>
        <th scope="row">Продукция</th>
        <td>
          <p class="text-secondary my-0">
            {{ stock_entry.get_product_type_display }}
            <i class="bi bi-caret-right-fill"></i> {{ stock_entry.product }}
            <i class="bi bi-caret-right-fill"></i> {{ stock_entry.subproduct }}
          </p>
          <p class="fw-bold my-0">
            {{ stock_entry.product_item_name }}
            {% if stock_entry.product_item %}
              <a href="{% url 'main:product_item_detail' stock_entry.product_item.id %}" title="Карточка наименования продукции"><i class="bi bi-eye"></i></a>
            {% endif %}
          </p>
        </td>
      </tr>
      <tr>
        <th scope="row">Остаток</th>
        <td>
          <span class="fw-bold">{{ stock_entry.volume.normalize }}&nbsp;{{ stock_entry.unit }}</span>
          {% if stock_entry.main.is_populated %}<span class="text-secondary"> / {{ stock_entry.main.initial_volume.normalize }}</span>{% endif %}
        </td>
      </tr>
      <tr>
        <th scope="row">Упаковка</th>
        <td>
          {% for package in stock_entry.package_set.all %}
            <p class="my-0">
              {{ package.get_level_display }}:
              {{ package.packing_type }} -
              {{ package.quantity }} шт
              <span class="text-secondary">{{ package.product_marks }}</span>
            </p>
          {% endfor %}
        </td>
      </tr>
      <tr>
        <th scope="row">Произведено</th>
        <td>
          {{ stock_entry.date_produced_display }}
        </td>
      </tr>
      <tr>
        <th scope="row">Срок годности</th>
        <td>
          <span class="{{ stock_entry.date_expiry_class }}">{{ stock_entry.date_expiry_display }}</span>
          {% if stock_entry.is_perishable %}<span class="badge text-bg-warning">СКОРОПОРТ</span>{% endif %}
        </td>
      </tr>
      {% if stock_entry.origin_country %}
        <tr>
          <th scope="row">Страна</th>
          <td>{{ stock_entry.origin_country }}</td>
        </tr>
      {% endif %}
      {% if stock_entry.producer_name %}
        <tr>
          <th scope="row">Производитель</th>
          <td>
            {% if stock_entry.producer %}<i class="bi bi-house text-info"></i>{% endif %}
            {{ stock_entry.producer_name }}
          </td>
        </tr>
      {% endif %}
      {% if stock_entry.stockentryvetdocument_set.count %}
        <tr>
          <th scope="row">Вет. документы</th>
          <td>
            {% for vet_document in stock_entry.stockentryvetdocument_set.all %}
              <p class="my-0">
                <a target="_blank" href="https://mercury.vetrf.ru/pub/operatorui?_action=findVetDocumentFormByUuid&uuid={{ vet_document.uuid }}">{{ vet_document.uuid }}</a>
                <a target="_blank" href="https://mercury.vetrf.ru/pub/operatorui?_action=printVetDocumentByUuid&uuid={{ vet_document.uuid }}"><i class="bi bi-printer"></i></a>
              </p>
            {% endfor %}
          </td>
        </tr>
      {% endif %}
      <tr>
        <th scope="row">
          Комментарий
        </th>
        <td>
          {% if stock_entry.main.comment_important %}<i class="bi bi-exclamation-square-fill text-warning"></i>{% endif %}
          {{ stock_entry.main.comment_text }}
          <a class="" data-bs-toggle="collapse" href="#collapseFilter" title="Изменить"><i class="bi bi-pencil-square"></i></a>
          <div class="collapse" id="collapseFilter">
            {% load django_bootstrap5 %}
            <form class="mt-3 form" method="POST">
              {% csrf_token %}
              {% bootstrap_field comment_form.text show_label='skip' %}
              {% bootstrap_field comment_form.important %}
              <button class="btn btn-primary" name="save_comment" type="submit">Сохранить</button>
            </form>
          </div>
        </td>
      </tr>
      <tr style="font-size: 75%">
        <th scope="row" class="text-secondary">Служебные</th>
        <td class="text-secondary">
          GUID: {{ stock_entry.guid }} <i class="bi bi-dash"></i>
          UUID: {{ stock_entry.uuid }} <i class="bi bi-dash"></i>
          ID: {{ stock_entry.id }}
        </td>
      </tr>
    </tbody>
  </table>

  <div class="mt-5 d-flex justify-content-between">
    <h4>История изменения записи</h4>
    <form method="POST" action="{% url 'main:vetis_task' %}">
      {% csrf_token %}
      <input type="hidden" name="stock_entry_id" value="{{ stock_entry.id }}" />
      <button class="btn btn-sm btn-secondary" name="vetis_task" value="reload_stock_entry_history"
        onclick="return window.confirm('Будут загружены данные с сайта Ветис. Вы уверены?')">
        Загрузить (обновить) историю
      </button>
    </form>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">&nbsp;</th>
        <th scope="col">Создана</th>
        <th scope="col">Изменена</th>
        <th scope="col">Причина</th>
        <th scope="col">Остаток</th>
      </tr>
    </thead>
    <tbody>
      {% for se in stock_entry_history %}
        {% if se.id == stock_entry.id %}
          <tr class="table-active">
        {% else %}
          <tr>
        {% endif %}
          <td>
            {% if se.id == stock_entry.id %}
              <i class="bi bi-arrow-right-square text-warning"></i>
            {% else %}
              <a href="{% url 'main:stock_entry_detail' se.id %}" title="Перейти к версии"><i class="bi bi-box-arrow-up-right"></i></a>
            {% endif %}
          </td>
          <td>{{ se.date_created }}</td>
          <td>{{ se.date_updated }}</td>
          <td>{{ se.get_status_display }}</td>
          <td>{{ se.volume.normalize }}&nbsp;{{ se.unit }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}